<?php
/* (C) Websplosion LTD., 2001-2014

IMPORTANT: This is a commercial software product
and any kind of using it must agree to the Websplosion's license agreement.
It can be found at http://www.chameleonsocial.com/license.doc

This notice may not be removed from the source code. */

$g['template_options'] = array(
    'set' => 'urban',
    'name' => 'urban',
    'type_payment_features' => 'urban',
    'login_by_mail' => 'Y',
    'login_page_template' => 'login.html',
    'register_page_template' => 'register.html',
    'register_location_by_ip' => 'Y',
    'map_on_main_page_urban' => 'Y',
    'main_page_frm_login_shadow_urban' => 'Y',
    'main_page_image_default_urban' => '5.jpg',
    'information_block_on_main_page_urban' => 'Y',
    'facebook_like_button' => 'Y',
    'tiled_footer_urban' => 'Y',
    'footer_tile_image_default_urban' => '1.png',
    'footer_image_urban' => 'Y',
    'footer_image_default_urban' => '1.png',
    'arrow_on_main_page_urban' => 'Y',
    'rate_see_my_photo_rating' => 'Y',
    'captcha_settings_custom' => 'Y',
    'logo_footer' => 'Y',
    'logo_w' => 287,
    'logo_h' => 60,
    'logo_footer_w' => 287,
    'logo_footer_h' => 60,
    'width_captcha' => 95,
    'height_captcha' => 24,
    'private_photo_by_template' => 'Y',
    'no_photo_by_template' => 'Y',
    'login_form_on' => 'Y',
    'profile_photo_w' => 217,
    'profile_plug_photo_h' => 299,
    'hide_site_sections' => array(
        'main_page_mode',
        'home_page_mode',
        'mode_profile',
        'feed_as_home_page',
        'allow_users_profile_mode',
    ),
    'profile_col_narrow' => 'Y',
    'fields_not_availableOLD' => array(133,134,136,137,139,140,142,144,145,146,148,149,150,152,154,155,156,157,158,160,162,163,164,165,166,167,168,169,170,348,468,471),
    'fields_not_available_admin' => array(133,134,136,137,139,140,142,144,145,146,148,149,150,152,154,155,156,157,158,160,162,163,164,165,166,167,168,169,170,348,468,471,485,494,708),
    'fields_not_available' => array(708),
	'fields_mode' => 'urban',
    'home_page' => 'profile_view.php',
    'redirect_wait_approval' => 'profile_view.php',
    'not_display_module' => array('complite', 'profile_menu', 'search', 'users_list_header_buttons', 'friends_menu', 'custom_head', 'profile_charts'),
    'custom_profile_html' => 'profile_html_urban',
    'list_users_filter' => 'Y',
    'usersinfo_per_page' => 'number_of_profiles_in_the_search_results',
    'usersinfo_pages_per_list' => 10,
    'list_users_info_ajax' => 'Y',
    'list_users_info_tmpl_parts' => 'Y',
    'list_users_custom_page' => 'Y',
    'user_block_per_page' => 1000,
    'list_users_viewed_me_tmpl_parts' => 'Y',
    'list_users_rated_me_tmpl_parts' => 'Y',
    'list_users_my_friends_tmpl_parts' => 'Y',
    'list_users_block_list_tmpl_parts' => 'Y',
    'user_custom_per_page' => 10,
    'viewed_me_custom_settings' => 'Y',
    'rated_me_custom_settings' => 'Y',
    'access_check_to_profile' => 'Y',
    'redirect_user_blocked' => 'Y',
    'hide_profile_settings' => array('set_can_comment_photos', 'color_scheme',
                                     'albums_to_see', 'default_online_view', 'autologin', 'smart_profile',
                                     'sound', 'framework_version', 'set_email_mail', 'set_notif_push_notifications',),
    'smooth_scroll' => 'Y',
    'do_not_show_me_in_search' => 'Y',
    'city_is_not_active' => 'Y',

    'banners_places' => array ('home' => 0,
                               'top' => 0,
                               'header' => 1,
                               'right_column' => 1,
                               'footer' => 1,
                               'footer_mobile' => 1,
                               'footer_additional' => 0,
                               'left_column' => 0),
    'menu_admin_banner' => 'Y',
    'upload_icon_field_i_am_here_to' => 'Y',
    'upload_icon_field_interests' => 'Y',
    'upload_icon_field_orientation' => 'N',
    'page_users_new_disabled' => 'Y',
    'custom_wall_show' => 'Y',

    'column_narrow_menu' => 'Y',
    'add_name_system_msg_general_chat' => 'Y',
    'wall_sections_only' => array('comment', 'photo', 'interests', 'pics', 'vids'),
);

Common::setOptionRuntime('none', 'home_page_mode');